PROCESSOR	P16F887
		INCLUDE		<P16F887.INC>

		__CONFIG _CONFIG1, (_INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOR_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF & _DEBUG_OFF)
		__CONFIG _CONFIG2, (_WRT_OFF & _BOR40V)

		ORG	0x00	

CON		EQU	0x20

        BANKSEL ANSEL		;CAMBIO BANCO 3
		CLRF 	ANSEL
		CLRF 	ANSELH
	
		BANKSEL	TRISA		;CAMBIO BANCO 1
		CLRF	TRISA	
		CLRF	TRISB
		CLRF	TRISC
		CLRF	TRISD
		CLRF	TRISE

		MOVLW 	0xD3		;VELOCIDAD ANIMACION
		MOVWF	OPTION_REG
		
; 		CLRF    ADRESH		;LIMPIAR ADRESH Y ADRESL
;    	CLRF    ADRESL

;    	MOVLW 	0xD5		;ADC1 PARA COORDENADAS PORTA
;    	MOVWF 	ADCON0
    
;   	MOVLW	0xD5		;ADC2 PARA COORDENADAS PORTC
;    	MOVWF   ADCON1

		BANKSEL	PORTA		;CAMBIO BANCO 0	

C_P		MOVLW	0x3C		;PRIMER INICIO DE NO. CICLOS PARA VISUALIZAR UN FRAME DE LA IMAGEN
		MOVWF	CON
		GOTO	FR1			;SALTA A LA PRIMER FUNCION DE FRAME PARA INICIAR
;**********************************
FR1							;FUNCION DEL FRAME NO. DE LA IMAGEN
		MOVLW	0x3C		;RA0
		MOVWF	PORTA
		MOVLW	0x01
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C0
		CALL	RET

		MOVLW	0x7E		;RA1
		MOVWF	PORTA
		MOVLW	0x02
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C1
		CALL	RET

		MOVLW	0xFF		;RA2
		MOVWF	PORTA
		MOVLW	0x04
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C2
		CALL	RET

		MOVLW	0xFF		;RA3
		MOVWF	PORTA
		MOVLW	0x08
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C3
		CALL	RET

		MOVLW	0xFF		;RA4
		MOVWF	PORTA
		MOVLW	0x10
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C4
		CALL	RET

		MOVLW	0xFF		;RA5
		MOVWF	PORTA
		MOVLW	0x20
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C5
		CALL	RET

		MOVLW	0x7E		;RA6
		MOVWF	PORTA
		MOVLW	0x40
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C6
		CALL	RET

		MOVLW	0x3C		;RA7
		MOVWF	PORTA
		MOVLW	0x80
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C7
		CALL	RET
		
		DECFSZ	CON,1
		GOTO	FR1
;**********************************
		MOVLW	0x3C			;NO. CICLOS PARA VISUALIZAR UN FRAME DE LA IMAGEN
		MOVWF	CON
FR2							;FUNCION DEL FRAME NO. DE LA IMAGEN
		MOVLW	0x3C		;RA0
		MOVWF	PORTA
		MOVLW	0x01
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C0
		CALL	RET

		MOVLW	0x7E		;RA1
		MOVWF	PORTA
		MOVLW	0x02
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C1
		CALL	RET

		MOVLW	0xFF		;RA2
		MOVWF	PORTA
		MOVLW	0x04
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C2
		CALL	RET

		MOVLW	0xFF		;RA3
		MOVWF	PORTA
		MOVLW	0x08
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C3
		CALL	RET

		MOVLW	0xFF		;RA4
		MOVWF	PORTA
		MOVLW	0x10
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C4
		CALL	RET

		MOVLW	0xFF		;RA5
		MOVWF	PORTA
		MOVLW	0x20
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C5
		CALL	RET

		MOVLW	0x7E		;RA6
		MOVWF	PORTA
		MOVLW	0x40
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C6
		CALL	RET

		MOVLW	0x24		;RA7
		MOVWF	PORTA
		MOVLW	0x80
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C7
		CALL	RET
		
		DECFSZ	CON,1
		GOTO	FR2
;**********************************	
		MOVLW	0x3C			;NO. CICLOS PARA VISUALIZAR UN FRAME DE LA IMAGEN
		MOVWF	CON
FR3							;FUNCION DEL FRAME NO. DE LA IMAGEN
		MOVLW	0x3C		;RA0
		MOVWF	PORTA
		MOVLW	0x01
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C0
		CALL	RET

		MOVLW	0x7E		;RA1
		MOVWF	PORTA
		MOVLW	0x02
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C1
		CALL	RET

		MOVLW	0xFF		;RA2
		MOVWF	PORTA
		MOVLW	0x04
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C2
		CALL	RET

		MOVLW	0xFF		;RA3
		MOVWF	PORTA
		MOVLW	0x08
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C3
		CALL	RET

		MOVLW	0xFF		;RA4
		MOVWF	PORTA
		MOVLW	0x10
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C4
		CALL	RET

		MOVLW	0xFF		;RA5
		MOVWF	PORTA
		MOVLW	0x20
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C5
		CALL	RET

		MOVLW	0xE7		;RA6
		MOVWF	PORTA
		MOVLW	0x40
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C6
		CALL	RET

		MOVLW	0x42		;RA7
		MOVWF	PORTA
		MOVLW	0x80
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C7
		CALL	RET
		
		DECFSZ	CON,1
		GOTO	FR3
;**********************************	
		MOVLW	0x3C			;NO. CICLOS PARA VISUALIZAR UN FRAME DE LA IMAGEN
		MOVWF	CON
FR4							;FUNCION DEL FRAME NO. DE LA IMAGEN
		MOVLW	0x3C		;RA0
		MOVWF	PORTA
		MOVLW	0x01
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C0
		CALL	RET

		MOVLW	0x7E		;RA1
		MOVWF	PORTA
		MOVLW	0x02
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C1
		CALL	RET

		MOVLW	0xFF		;RA2
		MOVWF	PORTA
		MOVLW	0x04
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C2
		CALL	RET

		MOVLW	0xFF		;RA3
		MOVWF	PORTA
		MOVLW	0x08
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C3
		CALL	RET

		MOVLW	0xFF		;RA4
		MOVWF	PORTA
		MOVLW	0x10
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C4
		CALL	RET

		MOVLW	0xE7		;RA5
		MOVWF	PORTA
		MOVLW	0x20
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C5
		CALL	RET

		MOVLW	0xC3		;RA6
		MOVWF	PORTA
		MOVLW	0x40
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C6
		CALL	RET

		MOVLW	0x81		;RA7
		MOVWF	PORTA
		MOVLW	0x80
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C7
		CALL	RET
		
		DECFSZ	CON,1
		GOTO	FR4	
;**********************************	
		MOVLW	0x3C			;NO. CICLOS PARA VISUALIZAR UN FRAME DE LA IMAGEN
		MOVWF	CON
FR5							;FUNCION DEL FRAME NO. DE LA IMAGEN
		MOVLW	0x3C		;RA0
		MOVWF	PORTA
		MOVLW	0x01
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C0
		CALL	RET

		MOVLW	0x7E		;RA1
		MOVWF	PORTA
		MOVLW	0x02
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C1
		CALL	RET

		MOVLW	0xFF		;RA2
		MOVWF	PORTA
		MOVLW	0x04
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C2
		CALL	RET

		MOVLW	0xFF		;RA3
		MOVWF	PORTA
		MOVLW	0x08
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C3
		CALL	RET

		MOVLW	0xFF		;RA4
		MOVWF	PORTA
		MOVLW	0x10
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C4
		CALL	RET

		MOVLW	0xFF		;RA5
		MOVWF	PORTA
		MOVLW	0x20
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C5
		CALL	RET

		MOVLW	0xE7		;RA6
		MOVWF	PORTA
		MOVLW	0x40
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C6
		CALL	RET

		MOVLW	0x42		;RA7
		MOVWF	PORTA
		MOVLW	0x80
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C7
		CALL	RET
		
		DECFSZ	CON,1
		GOTO	FR5
;**********************************
		MOVLW	0x3C			;NO. CICLOS PARA VISUALIZAR UN FRAME DE LA IMAGEN
		MOVWF	CON
FR6							;FUNCION DEL FRAME NO. DE LA IMAGEN
		MOVLW	0x3C		;RA0
		MOVWF	PORTA
		MOVLW	0x01
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C0
		CALL	RET

		MOVLW	0x7E		;RA1
		MOVWF	PORTA
		MOVLW	0x02
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C1
		CALL	RET

		MOVLW	0xFF		;RA2
		MOVWF	PORTA
		MOVLW	0x04
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C2
		CALL	RET

		MOVLW	0xFF		;RA3
		MOVWF	PORTA
		MOVLW	0x08
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C3
		CALL	RET

		MOVLW	0xFF		;RA4
		MOVWF	PORTA
		MOVLW	0x10
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C4
		CALL	RET

		MOVLW	0xFF		;RA5
		MOVWF	PORTA
		MOVLW	0x20
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C5
		CALL	RET

		MOVLW	0x7E		;RA6
		MOVWF	PORTA
		MOVLW	0x40
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C6
		CALL	RET

		MOVLW	0x24		;RA7
		MOVWF	PORTA
		MOVLW	0x80
		MOVWF	PORTC		;LEDS A ENCENDER EN LA FILA C7
		CALL	RET
		
		DECFSZ	CON,1
		GOTO	FR6
		
		GOTO	C_P

RET		MOVLW 	0x7F		
		MOVWF	TMR0
ET0IFX	BTFSS	INTCON,T0IF
		GOTO	ET0IFX
		BCF		INTCON,T0IF
		RETURN

		END