PROCESSOR	P16F887
		INCLUDE		<P16F887.INC>

__CONFIG _CONFIG1, (_INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOR_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF & _DEBUG_OFF)
__CONFIG _CONFIG2, (_WRT_OFF & _BOR40V)

NB	    EQU     0x21	
WM	    EQU     0x22
VA		EQU		0x23
VB		EQU		0x24
VC		EQU		0x25
VX		EQU		0x20
      
		ORG	0x00	
	
        BANKSEL ANSEL	;CAMBIO BANCO 3
		CLRF 	ANSEL
		CLRF 	ANSELH
	
		BANKSEL	TRISA	;CAMBIO BANCO 1
		CLRF	TRISA	
		MOVLW	0x10
		MOVWF	TRISA
		CLRF	TRISB
		CLRF	TRISC
		CLRF	TRISD
		CLRF	TRISE
		MOVLW	0xF0 
		MOVWF	OPTION_REG
	
		BANKSEL	PORTA	;CAMBIO BANCO 0

CP		MOVF	TMR0,W
		MOVWF	PORTA
	
		END