			PROCESSOR	P16F887
			INCLUDE		<P16F887.INC>

			__CONFIG _CONFIG1, (_INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOR_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF & _DEBUG_OFF)
			__CONFIG _CONFIG2, (_WRT_OFF & _BOR40V)

			VA	EQU	0x20	;ETIQUETAR RPG
			VB	EQU	0x21
      
			ORG	0x00	;VECTOR RESTAURACION
		
	        BANKSEL ANSEL	;CAMBIO BANCO 3
			CLRF 	ANSEL
			CLRF 	ANSELH
		
			BANKSEL	TRISA	;CAMBIO BANCO 1
			MOVLW	0xFF
			MOVWF	TRISB
			CLRF	TRISA
			CLRF	TRISC
			CLRF	TRISD
			CLRF	TRISE
		
			BANKSEL	PORTA	;CAMBIO BANCO 0

C_P:		MOVF	PORTB,W	;CICLO PRINCIPAL
			MOVWF	PORTA
			GOTO	C_P
		
			END		;FIN